<?php

if ( ! defined( 'ABSPATH' ) ) {
	die ( 'Forbidden' );
}

$cfg = array ();

$cfg ['page_builder'] = array (
		'title' => esc_html__( 'SLZ Pricing Box', 'slz' ),
		'description' => esc_html__( 'Box of pricing info', 'slz' ),
		'tab' => slz()->theme->manifest->get('name'),
		'icon' => 'icon-slzcore-pricing-box slz-vc-slzcore',
		'tag' => 'slz_pricing_box' 
);


$cfg ['default_value'] = array (
	'layout'                    => 'pricing-box',
	'column'                    => '1',
	'extra_class'               => '',
	'title1'                    => '',
	'title_color1'              => '',
	'price1'                    => '',
	'currency1'                 => '',
	'sub_title1'                => '',
	'sub_title_color1'          => '',
	'pricing_options1'          => '',
	'btn_text1'                 => '',
	'btn_text_color1'           => '',
	'btn_background_color1'     => '',
	'title2'                    => '',
	'title_color2'              => '',
	'price2'                    => '',
	'currency2'                 => '',
	'sub_title2'			    => '',
	'sub_title_color2' 			=> '',
	'pricing_options2' 			=> '',
	'btn_text2' 				=> '',
	'btn_text_color2'			=> '',
	'btn_background_color2' 	=> '',
	'title3' 					=> '',
	'title_color3'  			=> '',
	'price3' 					=> '',
	'currency3'  				=> '',
	'sub_title3'  				=> '',
	'sub_title_color3' 			=> '',
	'pricing_options3'  		=> '',
	'btn_text3' 				=> '',
	'btn_text_color3'  			=> '',
	'btn_background_color3'  	=> '',
	'title4'  					=> '',
	'title_color4'  			=> '',
	'price4'  					=> '',
	'currency4'  				=> '',
	'sub_title4' 				=> '',
	'sub_title_color4'  		=> '',
	'pricing_options4' 			=> '',
	'btn_text4'  				=> '',
	'btn_text_color4'  			=> '',
	'btn_background_color4'  	=> '',
	'active1'                   => 'no',
	'active2'                   => 'no',
	'active3'                   => 'no',
	'active4'                   => 'no',
	'label1'                    => '',
	'label2'                    => '',
	'label3'                    => '',
	'label4'                    => '',
	'btn_link1'                 => '',
	'btn_link2'                 => '',
	'btn_link3'                 => '',
	'btn_link4'                 => '',
	'btn_border_color1'         => '',
	'btn_border_color2'         => '',
	'btn_border_color3'         => '',
	'btn_border_color4'         => '',
	'active_color1'             => '',
	'active_color2'             => '',
	'active_color3'             => '',
	'active_color4'             => '',
	'label_text_color1'         => '',
	'label_text_color2'         => '',
	'label_text_color3'         => '',
	'label_text_color4'         => '',
	'label_background_color1'   => '',
	'label_background_color2'   => '',
	'label_background_color3'   => '',
	'label_background_color4'   => '',
	'unit1'                     => '',
	'unit2'                     => '',
	'unit3'                     => '',
	'unit4'                     => '',
	'price_color1'              => '',
	'price_color2'              => '',
	'price_color3'              => '',
	'price_color4'              => '',
	'price_subfix_color1'       => '',
	'price_subfix_color2'       => '',
	'price_subfix_color3'       => '',
	'price_subfix_color4'       => '',
	'separate1'                 => '',
	'separate2'                 => '',
	'separate3'                 => '',
	'separate4'                 => '',
);